/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '39516_work' at '16/03/03 19:21' with Gradle 2.8
 *
 * @author 39516_work, @date 16/03/03 19:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
